// <auto-generated>
/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using eZmaxApi.Client;
using eZmaxApi.Model;
using System.Diagnostics.CodeAnalysis;

namespace eZmaxApi.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IObjectBrandingApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        ObjectBrandingApiEvents Events { get; }

        /// <summary>
        /// Create a new Branding
        /// </summary>
        /// <remarks>
        /// The endpoint allows to create one or many elements at once.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="brandingCreateObjectV2Request"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingCreateObjectV2ApiResponse"/>&gt;</returns>
        Task<IBrandingCreateObjectV2ApiResponse> BrandingCreateObjectV2Async(BrandingCreateObjectV2Request brandingCreateObjectV2Request, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a new Branding
        /// </summary>
        /// <remarks>
        /// The endpoint allows to create one or many elements at once.
        /// </remarks>
        /// <param name="brandingCreateObjectV2Request"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingCreateObjectV2ApiResponse"/>?&gt;</returns>
        Task<IBrandingCreateObjectV2ApiResponse?> BrandingCreateObjectV2OrDefaultAsync(BrandingCreateObjectV2Request brandingCreateObjectV2Request, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Edit an existing Branding
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="pkiBrandingID"></param>
        /// <param name="brandingEditObjectV2Request"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingEditObjectV2ApiResponse"/>&gt;</returns>
        Task<IBrandingEditObjectV2ApiResponse> BrandingEditObjectV2Async(int pkiBrandingID, BrandingEditObjectV2Request brandingEditObjectV2Request, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Edit an existing Branding
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="pkiBrandingID"></param>
        /// <param name="brandingEditObjectV2Request"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingEditObjectV2ApiResponse"/>?&gt;</returns>
        Task<IBrandingEditObjectV2ApiResponse?> BrandingEditObjectV2OrDefaultAsync(int pkiBrandingID, BrandingEditObjectV2Request brandingEditObjectV2Request, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve Brandings and IDs
        /// </summary>
        /// <remarks>
        /// Get the list of Branding to be used in a dropdown or autocomplete control.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sSelector">The type of Brandings to return</param>
        /// <param name="eFilterActive">Specify which results we want to display. (optional, default to Active)</param>
        /// <param name="sQuery">Allow to filter the returned results (optional)</param>
        /// <param name="acceptLanguage"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetAutocompleteV2ApiResponse"/>&gt;</returns>
        Task<IBrandingGetAutocompleteV2ApiResponse> BrandingGetAutocompleteV2Async(string sSelector, Option<string> eFilterActive = default, Option<string> sQuery = default, Option<HeaderAcceptLanguage> acceptLanguage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve Brandings and IDs
        /// </summary>
        /// <remarks>
        /// Get the list of Branding to be used in a dropdown or autocomplete control.
        /// </remarks>
        /// <param name="sSelector">The type of Brandings to return</param>
        /// <param name="eFilterActive">Specify which results we want to display. (optional, default to Active)</param>
        /// <param name="sQuery">Allow to filter the returned results (optional)</param>
        /// <param name="acceptLanguage"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetAutocompleteV2ApiResponse"/>?&gt;</returns>
        Task<IBrandingGetAutocompleteV2ApiResponse?> BrandingGetAutocompleteV2OrDefaultAsync(string sSelector, Option<string> eFilterActive = default, Option<string> sQuery = default, Option<HeaderAcceptLanguage> acceptLanguage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve Branding list
        /// </summary>
        /// <remarks>
        /// Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |- --|- --| | eBrandingLogo | Default&lt;br&gt;JPEG&lt;br&gt;PNG | | eBrandingLogointerface | Default&lt;br&gt;JPEG&lt;br&gt;PNG |
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eOrderBy">Specify how you want the results to be sorted (optional)</param>
        /// <param name="iRowMax"> (optional)</param>
        /// <param name="iRowOffset"> (optional, default to 0)</param>
        /// <param name="acceptLanguage"> (optional)</param>
        /// <param name="sFilter"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetListV1ApiResponse"/>&gt;</returns>
        Task<IBrandingGetListV1ApiResponse> BrandingGetListV1Async(Option<string> eOrderBy = default, Option<int> iRowMax = default, Option<int> iRowOffset = default, Option<HeaderAcceptLanguage> acceptLanguage = default, Option<string> sFilter = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve Branding list
        /// </summary>
        /// <remarks>
        /// Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |- --|- --| | eBrandingLogo | Default&lt;br&gt;JPEG&lt;br&gt;PNG | | eBrandingLogointerface | Default&lt;br&gt;JPEG&lt;br&gt;PNG |
        /// </remarks>
        /// <param name="eOrderBy">Specify how you want the results to be sorted (optional)</param>
        /// <param name="iRowMax"> (optional)</param>
        /// <param name="iRowOffset"> (optional, default to 0)</param>
        /// <param name="acceptLanguage"> (optional)</param>
        /// <param name="sFilter"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetListV1ApiResponse"/>?&gt;</returns>
        Task<IBrandingGetListV1ApiResponse?> BrandingGetListV1OrDefaultAsync(Option<string> eOrderBy = default, Option<int> iRowMax = default, Option<int> iRowOffset = default, Option<HeaderAcceptLanguage> acceptLanguage = default, Option<string> sFilter = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve an existing Branding
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="pkiBrandingID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetObjectV3ApiResponse"/>&gt;</returns>
        Task<IBrandingGetObjectV3ApiResponse> BrandingGetObjectV3Async(int pkiBrandingID, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve an existing Branding
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="pkiBrandingID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetObjectV3ApiResponse"/>?&gt;</returns>
        Task<IBrandingGetObjectV3ApiResponse?> BrandingGetObjectV3OrDefaultAsync(int pkiBrandingID, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IBrandingCreateObjectV2ApiResponse"/>
    /// </summary>
    public interface IBrandingCreateObjectV2ApiResponse : eZmaxApi.Client.IApiResponse, ICreated<eZmaxApi.Model.BrandingCreateObjectV2Response?>
    {
        /// <summary>
        /// Returns true if the response is 201 Created
        /// </summary>
        /// <returns></returns>
        bool IsCreated { get; }
    }

    /// <summary>
    /// The <see cref="IBrandingEditObjectV2ApiResponse"/>
    /// </summary>
    public interface IBrandingEditObjectV2ApiResponse : eZmaxApi.Client.IApiResponse, IOk<eZmaxApi.Model.BrandingEditObjectV2Response?>, INotFound<eZmaxApi.Model.CommonResponseError?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// The <see cref="IBrandingGetAutocompleteV2ApiResponse"/>
    /// </summary>
    public interface IBrandingGetAutocompleteV2ApiResponse : eZmaxApi.Client.IApiResponse, IOk<eZmaxApi.Model.BrandingGetAutocompleteV2Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="IBrandingGetListV1ApiResponse"/>
    /// </summary>
    public interface IBrandingGetListV1ApiResponse : eZmaxApi.Client.IApiResponse, IOk<eZmaxApi.Model.BrandingGetListV1Response?>, INotAcceptable<eZmaxApi.Model.CommonResponseError?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 406 NotAcceptable
        /// </summary>
        /// <returns></returns>
        bool IsNotAcceptable { get; }
    }

    /// <summary>
    /// The <see cref="IBrandingGetObjectV3ApiResponse"/>
    /// </summary>
    public interface IBrandingGetObjectV3ApiResponse : eZmaxApi.Client.IApiResponse, IOk<eZmaxApi.Model.BrandingGetObjectV3Response?>, INotFound<eZmaxApi.Model.CommonResponseError?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class ObjectBrandingApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnBrandingCreateObjectV2;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorBrandingCreateObjectV2;

        internal void ExecuteOnBrandingCreateObjectV2(ObjectBrandingApi.BrandingCreateObjectV2ApiResponse apiResponse)
        {
            OnBrandingCreateObjectV2?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorBrandingCreateObjectV2(Exception exception)
        {
            OnErrorBrandingCreateObjectV2?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnBrandingEditObjectV2;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorBrandingEditObjectV2;

        internal void ExecuteOnBrandingEditObjectV2(ObjectBrandingApi.BrandingEditObjectV2ApiResponse apiResponse)
        {
            OnBrandingEditObjectV2?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorBrandingEditObjectV2(Exception exception)
        {
            OnErrorBrandingEditObjectV2?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnBrandingGetAutocompleteV2;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorBrandingGetAutocompleteV2;

        internal void ExecuteOnBrandingGetAutocompleteV2(ObjectBrandingApi.BrandingGetAutocompleteV2ApiResponse apiResponse)
        {
            OnBrandingGetAutocompleteV2?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorBrandingGetAutocompleteV2(Exception exception)
        {
            OnErrorBrandingGetAutocompleteV2?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnBrandingGetListV1;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorBrandingGetListV1;

        internal void ExecuteOnBrandingGetListV1(ObjectBrandingApi.BrandingGetListV1ApiResponse apiResponse)
        {
            OnBrandingGetListV1?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorBrandingGetListV1(Exception exception)
        {
            OnErrorBrandingGetListV1?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnBrandingGetObjectV3;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorBrandingGetObjectV3;

        internal void ExecuteOnBrandingGetObjectV3(ObjectBrandingApi.BrandingGetObjectV3ApiResponse apiResponse)
        {
            OnBrandingGetObjectV3?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorBrandingGetObjectV3(Exception exception)
        {
            OnErrorBrandingGetObjectV3?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class ObjectBrandingApi : IObjectBrandingApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<ObjectBrandingApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public ObjectBrandingApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectBrandingApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ObjectBrandingApi(ILogger<ObjectBrandingApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, ObjectBrandingApiEvents objectBrandingApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<ObjectBrandingApi>();
            HttpClient = httpClient;
            Events = objectBrandingApiEvents;
            ApiKeyProvider = apiKeyProvider;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatBrandingCreateObjectV2(BrandingCreateObjectV2Request brandingCreateObjectV2Request);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="brandingCreateObjectV2Request"></param>
        /// <returns></returns>
        private void ValidateBrandingCreateObjectV2(BrandingCreateObjectV2Request brandingCreateObjectV2Request)
        {
            if (brandingCreateObjectV2Request == null)
                throw new ArgumentNullException(nameof(brandingCreateObjectV2Request));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="brandingCreateObjectV2Request"></param>
        private void AfterBrandingCreateObjectV2DefaultImplementation(IBrandingCreateObjectV2ApiResponse apiResponseLocalVar, BrandingCreateObjectV2Request brandingCreateObjectV2Request)
        {
            bool suppressDefaultLog = false;
            AfterBrandingCreateObjectV2(ref suppressDefaultLog, apiResponseLocalVar, brandingCreateObjectV2Request);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="brandingCreateObjectV2Request"></param>
        partial void AfterBrandingCreateObjectV2(ref bool suppressDefaultLog, IBrandingCreateObjectV2ApiResponse apiResponseLocalVar, BrandingCreateObjectV2Request brandingCreateObjectV2Request);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="brandingCreateObjectV2Request"></param>
        private void OnErrorBrandingCreateObjectV2DefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, BrandingCreateObjectV2Request brandingCreateObjectV2Request)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorBrandingCreateObjectV2(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, brandingCreateObjectV2Request);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="brandingCreateObjectV2Request"></param>
        partial void OnErrorBrandingCreateObjectV2(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, BrandingCreateObjectV2Request brandingCreateObjectV2Request);

        /// <summary>
        /// Create a new Branding The endpoint allows to create one or many elements at once.
        /// </summary>
        /// <param name="brandingCreateObjectV2Request"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingCreateObjectV2ApiResponse"/>&gt;</returns>
        public async Task<IBrandingCreateObjectV2ApiResponse?> BrandingCreateObjectV2OrDefaultAsync(BrandingCreateObjectV2Request brandingCreateObjectV2Request, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await BrandingCreateObjectV2Async(brandingCreateObjectV2Request, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Create a new Branding The endpoint allows to create one or many elements at once.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="brandingCreateObjectV2Request"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingCreateObjectV2ApiResponse"/>&gt;</returns>
        public async Task<IBrandingCreateObjectV2ApiResponse> BrandingCreateObjectV2Async(BrandingCreateObjectV2Request brandingCreateObjectV2Request, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateBrandingCreateObjectV2(brandingCreateObjectV2Request);

                FormatBrandingCreateObjectV2(brandingCreateObjectV2Request);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/2/object/branding"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/2/object/branding");

                    httpRequestMessageLocalVar.Content = (brandingCreateObjectV2Request as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(brandingCreateObjectV2Request, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("Authorization", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<BrandingCreateObjectV2ApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<BrandingCreateObjectV2ApiResponse>();
                        BrandingCreateObjectV2ApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/2/object/branding", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterBrandingCreateObjectV2DefaultImplementation(apiResponseLocalVar, brandingCreateObjectV2Request);

                        Events.ExecuteOnBrandingCreateObjectV2(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorBrandingCreateObjectV2DefaultImplementation(e, "/2/object/branding", uriBuilderLocalVar.Path, brandingCreateObjectV2Request);
                Events.ExecuteOnErrorBrandingCreateObjectV2(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="BrandingCreateObjectV2ApiResponse"/>
        /// </summary>
        public partial class BrandingCreateObjectV2ApiResponse : eZmaxApi.Client.ApiResponse, IBrandingCreateObjectV2ApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<BrandingCreateObjectV2ApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="BrandingCreateObjectV2ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingCreateObjectV2ApiResponse(ILogger<BrandingCreateObjectV2ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="BrandingCreateObjectV2ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingCreateObjectV2ApiResponse(ILogger<BrandingCreateObjectV2ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public bool IsCreated => 201 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 201 Created
            /// </summary>
            /// <returns></returns>
            public eZmaxApi.Model.BrandingCreateObjectV2Response? Created()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsCreated
                    ? System.Text.Json.JsonSerializer.Deserialize<eZmaxApi.Model.BrandingCreateObjectV2Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 201 Created and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryCreated([NotNullWhen(true)]out eZmaxApi.Model.BrandingCreateObjectV2Response? result)
            {
                result = null;

                try
                {
                    result = Created();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)201);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatBrandingEditObjectV2(ref int pkiBrandingID, BrandingEditObjectV2Request brandingEditObjectV2Request);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="brandingEditObjectV2Request"></param>
        /// <returns></returns>
        private void ValidateBrandingEditObjectV2(BrandingEditObjectV2Request brandingEditObjectV2Request)
        {
            if (brandingEditObjectV2Request == null)
                throw new ArgumentNullException(nameof(brandingEditObjectV2Request));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="pkiBrandingID"></param>
        /// <param name="brandingEditObjectV2Request"></param>
        private void AfterBrandingEditObjectV2DefaultImplementation(IBrandingEditObjectV2ApiResponse apiResponseLocalVar, int pkiBrandingID, BrandingEditObjectV2Request brandingEditObjectV2Request)
        {
            bool suppressDefaultLog = false;
            AfterBrandingEditObjectV2(ref suppressDefaultLog, apiResponseLocalVar, pkiBrandingID, brandingEditObjectV2Request);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="pkiBrandingID"></param>
        /// <param name="brandingEditObjectV2Request"></param>
        partial void AfterBrandingEditObjectV2(ref bool suppressDefaultLog, IBrandingEditObjectV2ApiResponse apiResponseLocalVar, int pkiBrandingID, BrandingEditObjectV2Request brandingEditObjectV2Request);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="pkiBrandingID"></param>
        /// <param name="brandingEditObjectV2Request"></param>
        private void OnErrorBrandingEditObjectV2DefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int pkiBrandingID, BrandingEditObjectV2Request brandingEditObjectV2Request)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorBrandingEditObjectV2(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, pkiBrandingID, brandingEditObjectV2Request);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="pkiBrandingID"></param>
        /// <param name="brandingEditObjectV2Request"></param>
        partial void OnErrorBrandingEditObjectV2(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int pkiBrandingID, BrandingEditObjectV2Request brandingEditObjectV2Request);

        /// <summary>
        /// Edit an existing Branding 
        /// </summary>
        /// <param name="pkiBrandingID"></param>
        /// <param name="brandingEditObjectV2Request"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingEditObjectV2ApiResponse"/>&gt;</returns>
        public async Task<IBrandingEditObjectV2ApiResponse?> BrandingEditObjectV2OrDefaultAsync(int pkiBrandingID, BrandingEditObjectV2Request brandingEditObjectV2Request, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await BrandingEditObjectV2Async(pkiBrandingID, brandingEditObjectV2Request, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Edit an existing Branding 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="pkiBrandingID"></param>
        /// <param name="brandingEditObjectV2Request"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingEditObjectV2ApiResponse"/>&gt;</returns>
        public async Task<IBrandingEditObjectV2ApiResponse> BrandingEditObjectV2Async(int pkiBrandingID, BrandingEditObjectV2Request brandingEditObjectV2Request, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateBrandingEditObjectV2(brandingEditObjectV2Request);

                FormatBrandingEditObjectV2(ref pkiBrandingID, brandingEditObjectV2Request);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/2/object/branding/{pkiBrandingID}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/2/object/branding/{pkiBrandingID}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BpkiBrandingID%7D", Uri.EscapeDataString(pkiBrandingID.ToString()));

                    httpRequestMessageLocalVar.Content = (brandingEditObjectV2Request as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(brandingEditObjectV2Request, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("Authorization", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Put;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<BrandingEditObjectV2ApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<BrandingEditObjectV2ApiResponse>();
                        BrandingEditObjectV2ApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/2/object/branding/{pkiBrandingID}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterBrandingEditObjectV2DefaultImplementation(apiResponseLocalVar, pkiBrandingID, brandingEditObjectV2Request);

                        Events.ExecuteOnBrandingEditObjectV2(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorBrandingEditObjectV2DefaultImplementation(e, "/2/object/branding/{pkiBrandingID}", uriBuilderLocalVar.Path, pkiBrandingID, brandingEditObjectV2Request);
                Events.ExecuteOnErrorBrandingEditObjectV2(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="BrandingEditObjectV2ApiResponse"/>
        /// </summary>
        public partial class BrandingEditObjectV2ApiResponse : eZmaxApi.Client.ApiResponse, IBrandingEditObjectV2ApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<BrandingEditObjectV2ApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="BrandingEditObjectV2ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingEditObjectV2ApiResponse(ILogger<BrandingEditObjectV2ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="BrandingEditObjectV2ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingEditObjectV2ApiResponse(ILogger<BrandingEditObjectV2ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public eZmaxApi.Model.BrandingEditObjectV2Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<eZmaxApi.Model.BrandingEditObjectV2Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out eZmaxApi.Model.BrandingEditObjectV2Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public eZmaxApi.Model.CommonResponseError? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<eZmaxApi.Model.CommonResponseError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out eZmaxApi.Model.CommonResponseError? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatBrandingGetAutocompleteV2(ref string sSelector, ref Option<string> eFilterActive, ref Option<string> sQuery, ref Option<HeaderAcceptLanguage> acceptLanguage);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="sSelector"></param>
        /// <param name="eFilterActive"></param>
        /// <param name="sQuery"></param>
        /// <returns></returns>
        private void ValidateBrandingGetAutocompleteV2(string sSelector, Option<string> eFilterActive, Option<string> sQuery)
        {
            if (sSelector == null)
                throw new ArgumentNullException(nameof(sSelector));

            if (eFilterActive.IsSet && eFilterActive.Value == null)
                throw new ArgumentNullException(nameof(eFilterActive));

            if (sQuery.IsSet && sQuery.Value == null)
                throw new ArgumentNullException(nameof(sQuery));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="sSelector"></param>
        /// <param name="eFilterActive"></param>
        /// <param name="sQuery"></param>
        /// <param name="acceptLanguage"></param>
        private void AfterBrandingGetAutocompleteV2DefaultImplementation(IBrandingGetAutocompleteV2ApiResponse apiResponseLocalVar, string sSelector, Option<string> eFilterActive, Option<string> sQuery, Option<HeaderAcceptLanguage> acceptLanguage)
        {
            bool suppressDefaultLog = false;
            AfterBrandingGetAutocompleteV2(ref suppressDefaultLog, apiResponseLocalVar, sSelector, eFilterActive, sQuery, acceptLanguage);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="sSelector"></param>
        /// <param name="eFilterActive"></param>
        /// <param name="sQuery"></param>
        /// <param name="acceptLanguage"></param>
        partial void AfterBrandingGetAutocompleteV2(ref bool suppressDefaultLog, IBrandingGetAutocompleteV2ApiResponse apiResponseLocalVar, string sSelector, Option<string> eFilterActive, Option<string> sQuery, Option<HeaderAcceptLanguage> acceptLanguage);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="sSelector"></param>
        /// <param name="eFilterActive"></param>
        /// <param name="sQuery"></param>
        /// <param name="acceptLanguage"></param>
        private void OnErrorBrandingGetAutocompleteV2DefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string sSelector, Option<string> eFilterActive, Option<string> sQuery, Option<HeaderAcceptLanguage> acceptLanguage)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorBrandingGetAutocompleteV2(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, sSelector, eFilterActive, sQuery, acceptLanguage);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="sSelector"></param>
        /// <param name="eFilterActive"></param>
        /// <param name="sQuery"></param>
        /// <param name="acceptLanguage"></param>
        partial void OnErrorBrandingGetAutocompleteV2(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string sSelector, Option<string> eFilterActive, Option<string> sQuery, Option<HeaderAcceptLanguage> acceptLanguage);

        /// <summary>
        /// Retrieve Brandings and IDs Get the list of Branding to be used in a dropdown or autocomplete control.
        /// </summary>
        /// <param name="sSelector">The type of Brandings to return</param>
        /// <param name="eFilterActive">Specify which results we want to display. (optional, default to Active)</param>
        /// <param name="sQuery">Allow to filter the returned results (optional)</param>
        /// <param name="acceptLanguage"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetAutocompleteV2ApiResponse"/>&gt;</returns>
        public async Task<IBrandingGetAutocompleteV2ApiResponse?> BrandingGetAutocompleteV2OrDefaultAsync(string sSelector, Option<string> eFilterActive = default, Option<string> sQuery = default, Option<HeaderAcceptLanguage> acceptLanguage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await BrandingGetAutocompleteV2Async(sSelector, eFilterActive, sQuery, acceptLanguage, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Retrieve Brandings and IDs Get the list of Branding to be used in a dropdown or autocomplete control.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="sSelector">The type of Brandings to return</param>
        /// <param name="eFilterActive">Specify which results we want to display. (optional, default to Active)</param>
        /// <param name="sQuery">Allow to filter the returned results (optional)</param>
        /// <param name="acceptLanguage"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetAutocompleteV2ApiResponse"/>&gt;</returns>
        public async Task<IBrandingGetAutocompleteV2ApiResponse> BrandingGetAutocompleteV2Async(string sSelector, Option<string> eFilterActive = default, Option<string> sQuery = default, Option<HeaderAcceptLanguage> acceptLanguage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateBrandingGetAutocompleteV2(sSelector, eFilterActive, sQuery);

                FormatBrandingGetAutocompleteV2(ref sSelector, ref eFilterActive, ref sQuery, ref acceptLanguage);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/2/object/branding/getAutocomplete/{sSelector}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/2/object/branding/getAutocomplete/{sSelector}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BsSelector%7D", Uri.EscapeDataString(sSelector.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (eFilterActive.IsSet)
                        parseQueryStringLocalVar["eFilterActive"] = ClientUtils.ParameterToString(eFilterActive.Value);

                    if (sQuery.IsSet)
                        parseQueryStringLocalVar["sQuery"] = ClientUtils.ParameterToString(sQuery.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    if (acceptLanguage.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("Accept-Language", ClientUtils.ParameterToString(acceptLanguage.Value));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("Authorization", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<BrandingGetAutocompleteV2ApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<BrandingGetAutocompleteV2ApiResponse>();
                        BrandingGetAutocompleteV2ApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/2/object/branding/getAutocomplete/{sSelector}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterBrandingGetAutocompleteV2DefaultImplementation(apiResponseLocalVar, sSelector, eFilterActive, sQuery, acceptLanguage);

                        Events.ExecuteOnBrandingGetAutocompleteV2(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorBrandingGetAutocompleteV2DefaultImplementation(e, "/2/object/branding/getAutocomplete/{sSelector}", uriBuilderLocalVar.Path, sSelector, eFilterActive, sQuery, acceptLanguage);
                Events.ExecuteOnErrorBrandingGetAutocompleteV2(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="BrandingGetAutocompleteV2ApiResponse"/>
        /// </summary>
        public partial class BrandingGetAutocompleteV2ApiResponse : eZmaxApi.Client.ApiResponse, IBrandingGetAutocompleteV2ApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<BrandingGetAutocompleteV2ApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="BrandingGetAutocompleteV2ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingGetAutocompleteV2ApiResponse(ILogger<BrandingGetAutocompleteV2ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="BrandingGetAutocompleteV2ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingGetAutocompleteV2ApiResponse(ILogger<BrandingGetAutocompleteV2ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public eZmaxApi.Model.BrandingGetAutocompleteV2Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<eZmaxApi.Model.BrandingGetAutocompleteV2Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out eZmaxApi.Model.BrandingGetAutocompleteV2Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatBrandingGetListV1(ref Option<string> eOrderBy, ref Option<int> iRowMax, ref Option<int> iRowOffset, ref Option<HeaderAcceptLanguage> acceptLanguage, ref Option<string> sFilter);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="eOrderBy"></param>
        /// <param name="sFilter"></param>
        /// <returns></returns>
        private void ValidateBrandingGetListV1(Option<string> eOrderBy, Option<string> sFilter)
        {
            if (eOrderBy.IsSet && eOrderBy.Value == null)
                throw new ArgumentNullException(nameof(eOrderBy));

            if (sFilter.IsSet && sFilter.Value == null)
                throw new ArgumentNullException(nameof(sFilter));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="eOrderBy"></param>
        /// <param name="iRowMax"></param>
        /// <param name="iRowOffset"></param>
        /// <param name="acceptLanguage"></param>
        /// <param name="sFilter"></param>
        private void AfterBrandingGetListV1DefaultImplementation(IBrandingGetListV1ApiResponse apiResponseLocalVar, Option<string> eOrderBy, Option<int> iRowMax, Option<int> iRowOffset, Option<HeaderAcceptLanguage> acceptLanguage, Option<string> sFilter)
        {
            bool suppressDefaultLog = false;
            AfterBrandingGetListV1(ref suppressDefaultLog, apiResponseLocalVar, eOrderBy, iRowMax, iRowOffset, acceptLanguage, sFilter);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="eOrderBy"></param>
        /// <param name="iRowMax"></param>
        /// <param name="iRowOffset"></param>
        /// <param name="acceptLanguage"></param>
        /// <param name="sFilter"></param>
        partial void AfterBrandingGetListV1(ref bool suppressDefaultLog, IBrandingGetListV1ApiResponse apiResponseLocalVar, Option<string> eOrderBy, Option<int> iRowMax, Option<int> iRowOffset, Option<HeaderAcceptLanguage> acceptLanguage, Option<string> sFilter);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="eOrderBy"></param>
        /// <param name="iRowMax"></param>
        /// <param name="iRowOffset"></param>
        /// <param name="acceptLanguage"></param>
        /// <param name="sFilter"></param>
        private void OnErrorBrandingGetListV1DefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> eOrderBy, Option<int> iRowMax, Option<int> iRowOffset, Option<HeaderAcceptLanguage> acceptLanguage, Option<string> sFilter)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorBrandingGetListV1(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, eOrderBy, iRowMax, iRowOffset, acceptLanguage, sFilter);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="eOrderBy"></param>
        /// <param name="iRowMax"></param>
        /// <param name="iRowOffset"></param>
        /// <param name="acceptLanguage"></param>
        /// <param name="sFilter"></param>
        partial void OnErrorBrandingGetListV1(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> eOrderBy, Option<int> iRowMax, Option<int> iRowOffset, Option<HeaderAcceptLanguage> acceptLanguage, Option<string> sFilter);

        /// <summary>
        /// Retrieve Branding list Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |- --|- --| | eBrandingLogo | Default&lt;br&gt;JPEG&lt;br&gt;PNG | | eBrandingLogointerface | Default&lt;br&gt;JPEG&lt;br&gt;PNG |
        /// </summary>
        /// <param name="eOrderBy">Specify how you want the results to be sorted (optional)</param>
        /// <param name="iRowMax"> (optional)</param>
        /// <param name="iRowOffset"> (optional, default to 0)</param>
        /// <param name="acceptLanguage"> (optional)</param>
        /// <param name="sFilter"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetListV1ApiResponse"/>&gt;</returns>
        public async Task<IBrandingGetListV1ApiResponse?> BrandingGetListV1OrDefaultAsync(Option<string> eOrderBy = default, Option<int> iRowMax = default, Option<int> iRowOffset = default, Option<HeaderAcceptLanguage> acceptLanguage = default, Option<string> sFilter = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await BrandingGetListV1Async(eOrderBy, iRowMax, iRowOffset, acceptLanguage, sFilter, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Retrieve Branding list Enum values that can be filtered in query parameter *sFilter*:  | Variable | Valid values | |- --|- --| | eBrandingLogo | Default&lt;br&gt;JPEG&lt;br&gt;PNG | | eBrandingLogointerface | Default&lt;br&gt;JPEG&lt;br&gt;PNG |
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="eOrderBy">Specify how you want the results to be sorted (optional)</param>
        /// <param name="iRowMax"> (optional)</param>
        /// <param name="iRowOffset"> (optional, default to 0)</param>
        /// <param name="acceptLanguage"> (optional)</param>
        /// <param name="sFilter"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetListV1ApiResponse"/>&gt;</returns>
        public async Task<IBrandingGetListV1ApiResponse> BrandingGetListV1Async(Option<string> eOrderBy = default, Option<int> iRowMax = default, Option<int> iRowOffset = default, Option<HeaderAcceptLanguage> acceptLanguage = default, Option<string> sFilter = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateBrandingGetListV1(eOrderBy, sFilter);

                FormatBrandingGetListV1(ref eOrderBy, ref iRowMax, ref iRowOffset, ref acceptLanguage, ref sFilter);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/1/object/branding/getList"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/1/object/branding/getList");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (eOrderBy.IsSet)
                        parseQueryStringLocalVar["eOrderBy"] = ClientUtils.ParameterToString(eOrderBy.Value);

                    if (iRowMax.IsSet)
                        parseQueryStringLocalVar["iRowMax"] = ClientUtils.ParameterToString(iRowMax.Value);

                    if (iRowOffset.IsSet)
                        parseQueryStringLocalVar["iRowOffset"] = ClientUtils.ParameterToString(iRowOffset.Value);

                    if (sFilter.IsSet)
                        parseQueryStringLocalVar["sFilter"] = ClientUtils.ParameterToString(sFilter.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    if (acceptLanguage.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("Accept-Language", ClientUtils.ParameterToString(acceptLanguage.Value));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("Authorization", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<BrandingGetListV1ApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<BrandingGetListV1ApiResponse>();
                        BrandingGetListV1ApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/1/object/branding/getList", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterBrandingGetListV1DefaultImplementation(apiResponseLocalVar, eOrderBy, iRowMax, iRowOffset, acceptLanguage, sFilter);

                        Events.ExecuteOnBrandingGetListV1(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorBrandingGetListV1DefaultImplementation(e, "/1/object/branding/getList", uriBuilderLocalVar.Path, eOrderBy, iRowMax, iRowOffset, acceptLanguage, sFilter);
                Events.ExecuteOnErrorBrandingGetListV1(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="BrandingGetListV1ApiResponse"/>
        /// </summary>
        public partial class BrandingGetListV1ApiResponse : eZmaxApi.Client.ApiResponse, IBrandingGetListV1ApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<BrandingGetListV1ApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="BrandingGetListV1ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingGetListV1ApiResponse(ILogger<BrandingGetListV1ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="BrandingGetListV1ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingGetListV1ApiResponse(ILogger<BrandingGetListV1ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public eZmaxApi.Model.BrandingGetListV1Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<eZmaxApi.Model.BrandingGetListV1Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out eZmaxApi.Model.BrandingGetListV1Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 406 NotAcceptable
            /// </summary>
            /// <returns></returns>
            public bool IsNotAcceptable => 406 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 406 NotAcceptable
            /// </summary>
            /// <returns></returns>
            public eZmaxApi.Model.CommonResponseError? NotAcceptable()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotAcceptable
                    ? System.Text.Json.JsonSerializer.Deserialize<eZmaxApi.Model.CommonResponseError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 406 NotAcceptable and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotAcceptable([NotNullWhen(true)]out eZmaxApi.Model.CommonResponseError? result)
            {
                result = null;

                try
                {
                    result = NotAcceptable();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)406);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatBrandingGetObjectV3(ref int pkiBrandingID);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="pkiBrandingID"></param>
        private void AfterBrandingGetObjectV3DefaultImplementation(IBrandingGetObjectV3ApiResponse apiResponseLocalVar, int pkiBrandingID)
        {
            bool suppressDefaultLog = false;
            AfterBrandingGetObjectV3(ref suppressDefaultLog, apiResponseLocalVar, pkiBrandingID);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="pkiBrandingID"></param>
        partial void AfterBrandingGetObjectV3(ref bool suppressDefaultLog, IBrandingGetObjectV3ApiResponse apiResponseLocalVar, int pkiBrandingID);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="pkiBrandingID"></param>
        private void OnErrorBrandingGetObjectV3DefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int pkiBrandingID)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorBrandingGetObjectV3(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, pkiBrandingID);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="pkiBrandingID"></param>
        partial void OnErrorBrandingGetObjectV3(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int pkiBrandingID);

        /// <summary>
        /// Retrieve an existing Branding 
        /// </summary>
        /// <param name="pkiBrandingID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetObjectV3ApiResponse"/>&gt;</returns>
        public async Task<IBrandingGetObjectV3ApiResponse?> BrandingGetObjectV3OrDefaultAsync(int pkiBrandingID, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await BrandingGetObjectV3Async(pkiBrandingID, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Retrieve an existing Branding 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="pkiBrandingID"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IBrandingGetObjectV3ApiResponse"/>&gt;</returns>
        public async Task<IBrandingGetObjectV3ApiResponse> BrandingGetObjectV3Async(int pkiBrandingID, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatBrandingGetObjectV3(ref pkiBrandingID);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/3/object/branding/{pkiBrandingID}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/3/object/branding/{pkiBrandingID}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BpkiBrandingID%7D", Uri.EscapeDataString(pkiBrandingID.ToString()));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("Authorization", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<BrandingGetObjectV3ApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<BrandingGetObjectV3ApiResponse>();
                        BrandingGetObjectV3ApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/3/object/branding/{pkiBrandingID}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterBrandingGetObjectV3DefaultImplementation(apiResponseLocalVar, pkiBrandingID);

                        Events.ExecuteOnBrandingGetObjectV3(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorBrandingGetObjectV3DefaultImplementation(e, "/3/object/branding/{pkiBrandingID}", uriBuilderLocalVar.Path, pkiBrandingID);
                Events.ExecuteOnErrorBrandingGetObjectV3(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="BrandingGetObjectV3ApiResponse"/>
        /// </summary>
        public partial class BrandingGetObjectV3ApiResponse : eZmaxApi.Client.ApiResponse, IBrandingGetObjectV3ApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<BrandingGetObjectV3ApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="BrandingGetObjectV3ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingGetObjectV3ApiResponse(ILogger<BrandingGetObjectV3ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="BrandingGetObjectV3ApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public BrandingGetObjectV3ApiResponse(ILogger<BrandingGetObjectV3ApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public eZmaxApi.Model.BrandingGetObjectV3Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<eZmaxApi.Model.BrandingGetObjectV3Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out eZmaxApi.Model.BrandingGetObjectV3Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public eZmaxApi.Model.CommonResponseError? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<eZmaxApi.Model.CommonResponseError>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out eZmaxApi.Model.CommonResponseError? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
