/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.9
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test
{
    /// <summary>
    ///  Class for testing ApikeyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApikeyRequestTests
    {
        // TODO uncomment below to declare an instance variable for ApikeyRequest
        //private ApikeyRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApikeyRequest
            //instance = new ApikeyRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApikeyRequest
        /// </summary>
        [Test]
        public void ApikeyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ApikeyRequest
            //Assert.IsInstanceOf(typeof(ApikeyRequest), instance);
        }


        /// <summary>
        /// Test the property 'PkiApikeyID'
        /// </summary>
        [Test]
        public void PkiApikeyIDTest()
        {
            // TODO unit test for the property 'PkiApikeyID'
        }
        /// <summary>
        /// Test the property 'FkiUserID'
        /// </summary>
        [Test]
        public void FkiUserIDTest()
        {
            // TODO unit test for the property 'FkiUserID'
        }
        /// <summary>
        /// Test the property 'ObjApikeyDescription'
        /// </summary>
        [Test]
        public void ObjApikeyDescriptionTest()
        {
            // TODO unit test for the property 'ObjApikeyDescription'
        }

    }

}
