/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing BrandingGetObjectV2ResponseMPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BrandingGetObjectV2ResponseMPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BrandingGetObjectV2ResponseMPayload
        //private BrandingGetObjectV2ResponseMPayload instance;

        public BrandingGetObjectV2ResponseMPayloadTests()
        {
            // TODO uncomment below to create an instance of BrandingGetObjectV2ResponseMPayload
            //instance = new BrandingGetObjectV2ResponseMPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrandingGetObjectV2ResponseMPayload
        /// </summary>
        [Fact]
        public void BrandingGetObjectV2ResponseMPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" BrandingGetObjectV2ResponseMPayload
            //Assert.IsType<BrandingGetObjectV2ResponseMPayload>(instance);
        }

        /// <summary>
        /// Test the property 'ObjBranding'
        /// </summary>
        [Fact]
        public void ObjBrandingTest()
        {
            // TODO unit test for the property 'ObjBranding'
        }
    }
}
