/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.8
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test
{
    /// <summary>
    ///  Class for testing EzsignfolderDisposeEzsignfoldersV1Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EzsignfolderDisposeEzsignfoldersV1RequestTests
    {
        // TODO uncomment below to declare an instance variable for EzsignfolderDisposeEzsignfoldersV1Request
        //private EzsignfolderDisposeEzsignfoldersV1Request instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EzsignfolderDisposeEzsignfoldersV1Request
            //instance = new EzsignfolderDisposeEzsignfoldersV1Request();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EzsignfolderDisposeEzsignfoldersV1Request
        /// </summary>
        [Test]
        public void EzsignfolderDisposeEzsignfoldersV1RequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EzsignfolderDisposeEzsignfoldersV1Request
            //Assert.IsInstanceOf(typeof(EzsignfolderDisposeEzsignfoldersV1Request), instance);
        }


        /// <summary>
        /// Test the property 'APkiEzsignfolderID'
        /// </summary>
        [Test]
        public void APkiEzsignfolderIDTest()
        {
            // TODO unit test for the property 'APkiEzsignfolderID'
        }

    }

}
