/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test
{
    /// <summary>
    ///  Class for testing EzsigntemplatepackagesignerResponseCompound
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EzsigntemplatepackagesignerResponseCompoundTests
    {
        // TODO uncomment below to declare an instance variable for EzsigntemplatepackagesignerResponseCompound
        //private EzsigntemplatepackagesignerResponseCompound instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EzsigntemplatepackagesignerResponseCompound
            //instance = new EzsigntemplatepackagesignerResponseCompound();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EzsigntemplatepackagesignerResponseCompound
        /// </summary>
        [Test]
        public void EzsigntemplatepackagesignerResponseCompoundInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EzsigntemplatepackagesignerResponseCompound
            //Assert.IsInstanceOf(typeof(EzsigntemplatepackagesignerResponseCompound), instance);
        }


        /// <summary>
        /// Test the property 'PkiEzsigntemplatepackagesignerID'
        /// </summary>
        [Test]
        public void PkiEzsigntemplatepackagesignerIDTest()
        {
            // TODO unit test for the property 'PkiEzsigntemplatepackagesignerID'
        }
        /// <summary>
        /// Test the property 'FkiEzsigntemplatepackageID'
        /// </summary>
        [Test]
        public void FkiEzsigntemplatepackageIDTest()
        {
            // TODO unit test for the property 'FkiEzsigntemplatepackageID'
        }
        /// <summary>
        /// Test the property 'SEzsigntemplatepackagesignerDescription'
        /// </summary>
        [Test]
        public void SEzsigntemplatepackagesignerDescriptionTest()
        {
            // TODO unit test for the property 'SEzsigntemplatepackagesignerDescription'
        }

    }

}
