/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.10
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Api;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test
{
    /// <summary>
    ///  Class for testing EzsignsignerRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EzsignsignerRequestTests
    {
        // TODO uncomment below to declare an instance variable for EzsignsignerRequest
        //private EzsignsignerRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EzsignsignerRequest
            //instance = new EzsignsignerRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EzsignsignerRequest
        /// </summary>
        [Test]
        public void EzsignsignerRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EzsignsignerRequest
            //Assert.IsInstanceOf(typeof(EzsignsignerRequest), instance);
        }


        /// <summary>
        /// Test the property 'FkiUserlogintypeID'
        /// </summary>
        [Test]
        public void FkiUserlogintypeIDTest()
        {
            // TODO unit test for the property 'FkiUserlogintypeID'
        }
        /// <summary>
        /// Test the property 'FkiTaxassignmentID'
        /// </summary>
        [Test]
        public void FkiTaxassignmentIDTest()
        {
            // TODO unit test for the property 'FkiTaxassignmentID'
        }
        /// <summary>
        /// Test the property 'FkiSecretquestionID'
        /// </summary>
        [Test]
        public void FkiSecretquestionIDTest()
        {
            // TODO unit test for the property 'FkiSecretquestionID'
        }
        /// <summary>
        /// Test the property 'EEzsignsignerLogintype'
        /// </summary>
        [Test]
        public void EEzsignsignerLogintypeTest()
        {
            // TODO unit test for the property 'EEzsignsignerLogintype'
        }
        /// <summary>
        /// Test the property 'SEzsignsignerSecretanswer'
        /// </summary>
        [Test]
        public void SEzsignsignerSecretanswerTest()
        {
            // TODO unit test for the property 'SEzsignsignerSecretanswer'
        }

    }

}
