/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using eZmaxApi.Model;
using eZmaxApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace eZmaxApi.Test.Model
{
    /// <summary>
    ///  Class for testing EzsigntemplatedocumentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EzsigntemplatedocumentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EzsigntemplatedocumentResponse
        //private EzsigntemplatedocumentResponse instance;

        public EzsigntemplatedocumentResponseTests()
        {
            // TODO uncomment below to create an instance of EzsigntemplatedocumentResponse
            //instance = new EzsigntemplatedocumentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EzsigntemplatedocumentResponse
        /// </summary>
        [Fact]
        public void EzsigntemplatedocumentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EzsigntemplatedocumentResponse
            //Assert.IsType<EzsigntemplatedocumentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'PkiEzsigntemplatedocumentID'
        /// </summary>
        [Fact]
        public void PkiEzsigntemplatedocumentIDTest()
        {
            // TODO unit test for the property 'PkiEzsigntemplatedocumentID'
        }

        /// <summary>
        /// Test the property 'FkiEzsigntemplateID'
        /// </summary>
        [Fact]
        public void FkiEzsigntemplateIDTest()
        {
            // TODO unit test for the property 'FkiEzsigntemplateID'
        }

        /// <summary>
        /// Test the property 'SEzsigntemplatedocumentName'
        /// </summary>
        [Fact]
        public void SEzsigntemplatedocumentNameTest()
        {
            // TODO unit test for the property 'SEzsigntemplatedocumentName'
        }

        /// <summary>
        /// Test the property 'IEzsigntemplatedocumentPagetotal'
        /// </summary>
        [Fact]
        public void IEzsigntemplatedocumentPagetotalTest()
        {
            // TODO unit test for the property 'IEzsigntemplatedocumentPagetotal'
        }

        /// <summary>
        /// Test the property 'IEzsigntemplatedocumentSignaturetotal'
        /// </summary>
        [Fact]
        public void IEzsigntemplatedocumentSignaturetotalTest()
        {
            // TODO unit test for the property 'IEzsigntemplatedocumentSignaturetotal'
        }

        /// <summary>
        /// Test the property 'IEzsigntemplatedocumentFormfieldtotal'
        /// </summary>
        [Fact]
        public void IEzsigntemplatedocumentFormfieldtotalTest()
        {
            // TODO unit test for the property 'IEzsigntemplatedocumentFormfieldtotal'
        }

        /// <summary>
        /// Test the property 'BEzsigntemplatedocumentHassignedsignatures'
        /// </summary>
        [Fact]
        public void BEzsigntemplatedocumentHassignedsignaturesTest()
        {
            // TODO unit test for the property 'BEzsigntemplatedocumentHassignedsignatures'
        }
    }
}
