// <auto-generated>
/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using eZmaxApi.Client;

namespace eZmaxApi.Model
{
    /// <summary>
    /// A Agent AutocompleteElement Response
    /// </summary>
    public partial class AgentAutocompleteElementResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentAutocompleteElementResponse" /> class.
        /// </summary>
        /// <param name="pkiAgentID">The unique ID of the Agent.</param>
        /// <param name="fkiDepartmentID">The unique ID of the Department</param>
        /// <param name="sContactFirstname">The First name of the contact</param>
        /// <param name="sContactLastname">The Last name of the contact</param>
        /// <param name="bAgentIsactive">Whether the Agent is active or not</param>
        [JsonConstructor]
        public AgentAutocompleteElementResponse(int pkiAgentID, int fkiDepartmentID, string sContactFirstname, string sContactLastname, bool bAgentIsactive)
        {
            PkiAgentID = pkiAgentID;
            FkiDepartmentID = fkiDepartmentID;
            SContactFirstname = sContactFirstname;
            SContactLastname = sContactLastname;
            BAgentIsactive = bAgentIsactive;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The unique ID of the Agent.
        /// </summary>
        /// <value>The unique ID of the Agent.</value>
        /* <example>1</example> */
        [JsonPropertyName("pkiAgentID")]
        public int PkiAgentID { get; set; }

        /// <summary>
        /// The unique ID of the Department
        /// </summary>
        /// <value>The unique ID of the Department</value>
        /* <example>21</example> */
        [JsonPropertyName("fkiDepartmentID")]
        public int FkiDepartmentID { get; set; }

        /// <summary>
        /// The First name of the contact
        /// </summary>
        /// <value>The First name of the contact</value>
        /* <example>John</example> */
        [JsonPropertyName("sContactFirstname")]
        public string SContactFirstname { get; set; }

        /// <summary>
        /// The Last name of the contact
        /// </summary>
        /// <value>The Last name of the contact</value>
        /* <example>Doe</example> */
        [JsonPropertyName("sContactLastname")]
        public string SContactLastname { get; set; }

        /// <summary>
        /// Whether the Agent is active or not
        /// </summary>
        /// <value>Whether the Agent is active or not</value>
        /* <example>true</example> */
        [JsonPropertyName("bAgentIsactive")]
        public bool BAgentIsactive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AgentAutocompleteElementResponse {\n");
            sb.Append("  PkiAgentID: ").Append(PkiAgentID).Append("\n");
            sb.Append("  FkiDepartmentID: ").Append(FkiDepartmentID).Append("\n");
            sb.Append("  SContactFirstname: ").Append(SContactFirstname).Append("\n");
            sb.Append("  SContactLastname: ").Append(SContactLastname).Append("\n");
            sb.Append("  BAgentIsactive: ").Append(BAgentIsactive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PkiAgentID (int) minimum
            if (this.PkiAgentID < (int)0)
            {
                yield return new ValidationResult("Invalid value for PkiAgentID, must be a value greater than or equal to 0.", new [] { "PkiAgentID" });
            }

            // FkiDepartmentID (int) minimum
            if (this.FkiDepartmentID < (int)0)
            {
                yield return new ValidationResult("Invalid value for FkiDepartmentID, must be a value greater than or equal to 0.", new [] { "FkiDepartmentID" });
            }

            if (this.SContactFirstname != null) {
                // SContactFirstname (string) pattern
                Regex regexSContactFirstname = new Regex(@"^.{1,20}$", RegexOptions.CultureInvariant);

                if (!regexSContactFirstname.Match(this.SContactFirstname).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SContactFirstname, must match a pattern of " + regexSContactFirstname, new [] { "SContactFirstname" });
                }
            }

            if (this.SContactLastname != null) {
                // SContactLastname (string) pattern
                Regex regexSContactLastname = new Regex(@"^.{1,25}$", RegexOptions.CultureInvariant);

                if (!regexSContactLastname.Match(this.SContactLastname).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SContactLastname, must match a pattern of " + regexSContactLastname, new [] { "SContactLastname" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AgentAutocompleteElementResponse" />
    /// </summary>
    public class AgentAutocompleteElementResponseJsonConverter : JsonConverter<AgentAutocompleteElementResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="AgentAutocompleteElementResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AgentAutocompleteElementResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> pkiAgentID = default;
            Option<int?> fkiDepartmentID = default;
            Option<string?> sContactFirstname = default;
            Option<string?> sContactLastname = default;
            Option<bool?> bAgentIsactive = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "pkiAgentID":
                            pkiAgentID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "fkiDepartmentID":
                            fkiDepartmentID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "sContactFirstname":
                            sContactFirstname = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sContactLastname":
                            sContactLastname = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "bAgentIsactive":
                            bAgentIsactive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!pkiAgentID.IsSet)
                throw new ArgumentException("Property is required for class AgentAutocompleteElementResponse.", nameof(pkiAgentID));

            if (!fkiDepartmentID.IsSet)
                throw new ArgumentException("Property is required for class AgentAutocompleteElementResponse.", nameof(fkiDepartmentID));

            if (!sContactFirstname.IsSet)
                throw new ArgumentException("Property is required for class AgentAutocompleteElementResponse.", nameof(sContactFirstname));

            if (!sContactLastname.IsSet)
                throw new ArgumentException("Property is required for class AgentAutocompleteElementResponse.", nameof(sContactLastname));

            if (!bAgentIsactive.IsSet)
                throw new ArgumentException("Property is required for class AgentAutocompleteElementResponse.", nameof(bAgentIsactive));

            if (pkiAgentID.IsSet && pkiAgentID.Value == null)
                throw new ArgumentNullException(nameof(pkiAgentID), "Property is not nullable for class AgentAutocompleteElementResponse.");

            if (fkiDepartmentID.IsSet && fkiDepartmentID.Value == null)
                throw new ArgumentNullException(nameof(fkiDepartmentID), "Property is not nullable for class AgentAutocompleteElementResponse.");

            if (sContactFirstname.IsSet && sContactFirstname.Value == null)
                throw new ArgumentNullException(nameof(sContactFirstname), "Property is not nullable for class AgentAutocompleteElementResponse.");

            if (sContactLastname.IsSet && sContactLastname.Value == null)
                throw new ArgumentNullException(nameof(sContactLastname), "Property is not nullable for class AgentAutocompleteElementResponse.");

            if (bAgentIsactive.IsSet && bAgentIsactive.Value == null)
                throw new ArgumentNullException(nameof(bAgentIsactive), "Property is not nullable for class AgentAutocompleteElementResponse.");

            return new AgentAutocompleteElementResponse(pkiAgentID.Value!.Value!, fkiDepartmentID.Value!.Value!, sContactFirstname.Value!, sContactLastname.Value!, bAgentIsactive.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AgentAutocompleteElementResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="agentAutocompleteElementResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AgentAutocompleteElementResponse agentAutocompleteElementResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, agentAutocompleteElementResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AgentAutocompleteElementResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="agentAutocompleteElementResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AgentAutocompleteElementResponse agentAutocompleteElementResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (agentAutocompleteElementResponse.SContactFirstname == null)
                throw new ArgumentNullException(nameof(agentAutocompleteElementResponse.SContactFirstname), "Property is required for class AgentAutocompleteElementResponse.");

            if (agentAutocompleteElementResponse.SContactLastname == null)
                throw new ArgumentNullException(nameof(agentAutocompleteElementResponse.SContactLastname), "Property is required for class AgentAutocompleteElementResponse.");

            writer.WriteNumber("pkiAgentID", agentAutocompleteElementResponse.PkiAgentID);

            writer.WriteNumber("fkiDepartmentID", agentAutocompleteElementResponse.FkiDepartmentID);

            writer.WriteString("sContactFirstname", agentAutocompleteElementResponse.SContactFirstname);

            writer.WriteString("sContactLastname", agentAutocompleteElementResponse.SContactLastname);

            writer.WriteBoolean("bAgentIsactive", agentAutocompleteElementResponse.BAgentIsactive);
        }
    }
}
