/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = eZmaxApi.Client.OpenAPIDateConverter;

namespace eZmaxApi.Model
{
    /// <summary>
    /// Payload for POST /1/object/communication
    /// </summary>
    [DataContract(Name = "communication-createObject-v1-Response-mPayload")]
    public partial class CommunicationCreateObjectV1ResponseMPayload : IEquatable<CommunicationCreateObjectV1ResponseMPayload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommunicationCreateObjectV1ResponseMPayload" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CommunicationCreateObjectV1ResponseMPayload() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CommunicationCreateObjectV1ResponseMPayload" /> class.
        /// </summary>
        /// <param name="aPkiCommunicationID">An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request. (required).</param>
        public CommunicationCreateObjectV1ResponseMPayload(List<int> aPkiCommunicationID = default(List<int>))
        {
            // to ensure "aPkiCommunicationID" is required (not null)
            if (aPkiCommunicationID == null)
            {
                throw new ArgumentNullException("aPkiCommunicationID is a required property for CommunicationCreateObjectV1ResponseMPayload and cannot be null");
            }
            this.APkiCommunicationID = aPkiCommunicationID;
        }

        /// <summary>
        /// An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
        /// </summary>
        /// <value>An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.</value>
        [DataMember(Name = "a_pkiCommunicationID", IsRequired = true, EmitDefaultValue = true)]
        public List<int> APkiCommunicationID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CommunicationCreateObjectV1ResponseMPayload {\n");
            sb.Append("  APkiCommunicationID: ").Append(APkiCommunicationID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CommunicationCreateObjectV1ResponseMPayload);
        }

        /// <summary>
        /// Returns true if CommunicationCreateObjectV1ResponseMPayload instances are equal
        /// </summary>
        /// <param name="input">Instance of CommunicationCreateObjectV1ResponseMPayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommunicationCreateObjectV1ResponseMPayload input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.APkiCommunicationID == input.APkiCommunicationID ||
                    this.APkiCommunicationID != null &&
                    input.APkiCommunicationID != null &&
                    this.APkiCommunicationID.SequenceEqual(input.APkiCommunicationID)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.APkiCommunicationID != null)
                {
                    hashCode = (hashCode * 59) + this.APkiCommunicationID.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
