/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenAPIDateConverter = eZmaxApi.Client.OpenAPIDateConverter;

namespace eZmaxApi.Model
{
    /// <summary>
    /// Request for PUT /1/object/cors/{pkiCorsID}
    /// </summary>
    [DataContract]
    public partial class CorsEditObjectV1Request :  IEquatable<CorsEditObjectV1Request>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CorsEditObjectV1Request" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CorsEditObjectV1Request() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CorsEditObjectV1Request" /> class.
        /// </summary>
        /// <param name="objCors">objCors (required).</param>
        public CorsEditObjectV1Request(CorsRequestCompound objCors = default(CorsRequestCompound))
        {
            // to ensure "objCors" is required (not null)
            if (objCors == null)
            {
                throw new InvalidDataException("objCors is a required property for CorsEditObjectV1Request and cannot be null");
            }
            else
            {
                this.ObjCors = objCors;
            }

        }

        /// <summary>
        /// Gets or Sets ObjCors
        /// </summary>
        [DataMember(Name="objCors", EmitDefaultValue=true)]
        public CorsRequestCompound ObjCors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CorsEditObjectV1Request {\n");
            sb.Append("  ObjCors: ").Append(ObjCors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CorsEditObjectV1Request);
        }

        /// <summary>
        /// Returns true if CorsEditObjectV1Request instances are equal
        /// </summary>
        /// <param name="input">Instance of CorsEditObjectV1Request to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CorsEditObjectV1Request input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ObjCors == input.ObjCors ||
                    (this.ObjCors != null &&
                    this.ObjCors.Equals(input.ObjCors))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ObjCors != null)
                    hashCode = hashCode * 59 + this.ObjCors.GetHashCode();
                return hashCode;
            }
        }
    }

}
