// <auto-generated>
/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using eZmaxApi.Client;

namespace eZmaxApi.Model
{
    /// <summary>
    /// A Ezmaxinvoicingsummaryexternal Object
    /// </summary>
    public partial class EzmaxinvoicingsummaryexternalResponseCompound : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EzmaxinvoicingsummaryexternalResponseCompound" /> class.
        /// </summary>
        /// <param name="fkiBillingentityexternalID">The unique ID of the Billingentityexternal</param>
        /// <param name="sBillingentityexternalDescription">The description of the Billingentityexternal</param>
        /// <param name="sEzmaxinvoicingsummaryexternalDescription">The description of the Ezmaxinvoicingsummaryexternal</param>
        /// <param name="aObjEzmaxinvoicingsummaryexternaldetail">aObjEzmaxinvoicingsummaryexternaldetail</param>
        /// <param name="pkiEzmaxinvoicingsummaryexternalID">The unique ID of the Ezmaxinvoicingsummaryexternal</param>
        /// <param name="fkiEzmaxinvoicingID">The unique ID of the Ezmaxinvoicing</param>
        [JsonConstructor]
        public EzmaxinvoicingsummaryexternalResponseCompound(int fkiBillingentityexternalID, string sBillingentityexternalDescription, string sEzmaxinvoicingsummaryexternalDescription, List<EzmaxinvoicingsummaryexternaldetailResponseCompound> aObjEzmaxinvoicingsummaryexternaldetail, Option<int?> pkiEzmaxinvoicingsummaryexternalID = default, Option<int?> fkiEzmaxinvoicingID = default)
        {
            FkiBillingentityexternalID = fkiBillingentityexternalID;
            SBillingentityexternalDescription = sBillingentityexternalDescription;
            SEzmaxinvoicingsummaryexternalDescription = sEzmaxinvoicingsummaryexternalDescription;
            AObjEzmaxinvoicingsummaryexternaldetail = aObjEzmaxinvoicingsummaryexternaldetail;
            PkiEzmaxinvoicingsummaryexternalIDOption = pkiEzmaxinvoicingsummaryexternalID;
            FkiEzmaxinvoicingIDOption = fkiEzmaxinvoicingID;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The unique ID of the Billingentityexternal
        /// </summary>
        /// <value>The unique ID of the Billingentityexternal</value>
        /* <example>83</example> */
        [JsonPropertyName("fkiBillingentityexternalID")]
        public int FkiBillingentityexternalID { get; set; }

        /// <summary>
        /// The description of the Billingentityexternal
        /// </summary>
        /// <value>The description of the Billingentityexternal</value>
        /* <example>ACME Inc</example> */
        [JsonPropertyName("sBillingentityexternalDescription")]
        public string SBillingentityexternalDescription { get; set; }

        /// <summary>
        /// The description of the Ezmaxinvoicingsummaryexternal
        /// </summary>
        /// <value>The description of the Ezmaxinvoicingsummaryexternal</value>
        /* <example>Company Demo</example> */
        [JsonPropertyName("sEzmaxinvoicingsummaryexternalDescription")]
        public string SEzmaxinvoicingsummaryexternalDescription { get; set; }

        /// <summary>
        /// Gets or Sets AObjEzmaxinvoicingsummaryexternaldetail
        /// </summary>
        [JsonPropertyName("a_objEzmaxinvoicingsummaryexternaldetail")]
        public List<EzmaxinvoicingsummaryexternaldetailResponseCompound> AObjEzmaxinvoicingsummaryexternaldetail { get; set; }

        /// <summary>
        /// Used to track the state of PkiEzmaxinvoicingsummaryexternalID
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PkiEzmaxinvoicingsummaryexternalIDOption { get; private set; }

        /// <summary>
        /// The unique ID of the Ezmaxinvoicingsummaryexternal
        /// </summary>
        /// <value>The unique ID of the Ezmaxinvoicingsummaryexternal</value>
        /* <example>177</example> */
        [JsonPropertyName("pkiEzmaxinvoicingsummaryexternalID")]
        public int? PkiEzmaxinvoicingsummaryexternalID { get { return this.PkiEzmaxinvoicingsummaryexternalIDOption; } set { this.PkiEzmaxinvoicingsummaryexternalIDOption = new(value); } }

        /// <summary>
        /// Used to track the state of FkiEzmaxinvoicingID
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FkiEzmaxinvoicingIDOption { get; private set; }

        /// <summary>
        /// The unique ID of the Ezmaxinvoicing
        /// </summary>
        /// <value>The unique ID of the Ezmaxinvoicing</value>
        /* <example>28</example> */
        [JsonPropertyName("fkiEzmaxinvoicingID")]
        public int? FkiEzmaxinvoicingID { get { return this.FkiEzmaxinvoicingIDOption; } set { this.FkiEzmaxinvoicingIDOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EzmaxinvoicingsummaryexternalResponseCompound {\n");
            sb.Append("  FkiBillingentityexternalID: ").Append(FkiBillingentityexternalID).Append("\n");
            sb.Append("  SBillingentityexternalDescription: ").Append(SBillingentityexternalDescription).Append("\n");
            sb.Append("  SEzmaxinvoicingsummaryexternalDescription: ").Append(SEzmaxinvoicingsummaryexternalDescription).Append("\n");
            sb.Append("  AObjEzmaxinvoicingsummaryexternaldetail: ").Append(AObjEzmaxinvoicingsummaryexternaldetail).Append("\n");
            sb.Append("  PkiEzmaxinvoicingsummaryexternalID: ").Append(PkiEzmaxinvoicingsummaryexternalID).Append("\n");
            sb.Append("  FkiEzmaxinvoicingID: ").Append(FkiEzmaxinvoicingID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // FkiBillingentityexternalID (int) minimum
            if (this.FkiBillingentityexternalID < (int)1)
            {
                yield return new ValidationResult("Invalid value for FkiBillingentityexternalID, must be a value greater than or equal to 1.", new [] { "FkiBillingentityexternalID" });
            }

            // SEzmaxinvoicingsummaryexternalDescription (string) maxLength
            if (this.SEzmaxinvoicingsummaryexternalDescription != null && this.SEzmaxinvoicingsummaryexternalDescription.Length > 70)
            {
                yield return new ValidationResult("Invalid value for SEzmaxinvoicingsummaryexternalDescription, length must be less than 70.", new [] { "SEzmaxinvoicingsummaryexternalDescription" });
            }

            // PkiEzmaxinvoicingsummaryexternalID (int) minimum
            if (this.PkiEzmaxinvoicingsummaryexternalIDOption.IsSet && this.PkiEzmaxinvoicingsummaryexternalIDOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for PkiEzmaxinvoicingsummaryexternalID, must be a value greater than or equal to 0.", new [] { "PkiEzmaxinvoicingsummaryexternalID" });
            }

            // FkiEzmaxinvoicingID (int) minimum
            if (this.FkiEzmaxinvoicingIDOption.IsSet && this.FkiEzmaxinvoicingIDOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for FkiEzmaxinvoicingID, must be a value greater than or equal to 0.", new [] { "FkiEzmaxinvoicingID" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EzmaxinvoicingsummaryexternalResponseCompound" />
    /// </summary>
    public class EzmaxinvoicingsummaryexternalResponseCompoundJsonConverter : JsonConverter<EzmaxinvoicingsummaryexternalResponseCompound>
    {
        /// <summary>
        /// Deserializes json to <see cref="EzmaxinvoicingsummaryexternalResponseCompound" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EzmaxinvoicingsummaryexternalResponseCompound Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> fkiBillingentityexternalID = default;
            Option<string?> sBillingentityexternalDescription = default;
            Option<string?> sEzmaxinvoicingsummaryexternalDescription = default;
            Option<List<EzmaxinvoicingsummaryexternaldetailResponseCompound>?> aObjEzmaxinvoicingsummaryexternaldetail = default;
            Option<int?> pkiEzmaxinvoicingsummaryexternalID = default;
            Option<int?> fkiEzmaxinvoicingID = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "fkiBillingentityexternalID":
                            fkiBillingentityexternalID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "sBillingentityexternalDescription":
                            sBillingentityexternalDescription = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sEzmaxinvoicingsummaryexternalDescription":
                            sEzmaxinvoicingsummaryexternalDescription = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "a_objEzmaxinvoicingsummaryexternaldetail":
                            aObjEzmaxinvoicingsummaryexternaldetail = new Option<List<EzmaxinvoicingsummaryexternaldetailResponseCompound>?>(JsonSerializer.Deserialize<List<EzmaxinvoicingsummaryexternaldetailResponseCompound>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "pkiEzmaxinvoicingsummaryexternalID":
                            pkiEzmaxinvoicingsummaryexternalID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "fkiEzmaxinvoicingID":
                            fkiEzmaxinvoicingID = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!fkiBillingentityexternalID.IsSet)
                throw new ArgumentException("Property is required for class EzmaxinvoicingsummaryexternalResponseCompound.", nameof(fkiBillingentityexternalID));

            if (!sBillingentityexternalDescription.IsSet)
                throw new ArgumentException("Property is required for class EzmaxinvoicingsummaryexternalResponseCompound.", nameof(sBillingentityexternalDescription));

            if (!sEzmaxinvoicingsummaryexternalDescription.IsSet)
                throw new ArgumentException("Property is required for class EzmaxinvoicingsummaryexternalResponseCompound.", nameof(sEzmaxinvoicingsummaryexternalDescription));

            if (!aObjEzmaxinvoicingsummaryexternaldetail.IsSet)
                throw new ArgumentException("Property is required for class EzmaxinvoicingsummaryexternalResponseCompound.", nameof(aObjEzmaxinvoicingsummaryexternaldetail));

            if (fkiBillingentityexternalID.IsSet && fkiBillingentityexternalID.Value == null)
                throw new ArgumentNullException(nameof(fkiBillingentityexternalID), "Property is not nullable for class EzmaxinvoicingsummaryexternalResponseCompound.");

            if (sBillingentityexternalDescription.IsSet && sBillingentityexternalDescription.Value == null)
                throw new ArgumentNullException(nameof(sBillingentityexternalDescription), "Property is not nullable for class EzmaxinvoicingsummaryexternalResponseCompound.");

            if (sEzmaxinvoicingsummaryexternalDescription.IsSet && sEzmaxinvoicingsummaryexternalDescription.Value == null)
                throw new ArgumentNullException(nameof(sEzmaxinvoicingsummaryexternalDescription), "Property is not nullable for class EzmaxinvoicingsummaryexternalResponseCompound.");

            if (aObjEzmaxinvoicingsummaryexternaldetail.IsSet && aObjEzmaxinvoicingsummaryexternaldetail.Value == null)
                throw new ArgumentNullException(nameof(aObjEzmaxinvoicingsummaryexternaldetail), "Property is not nullable for class EzmaxinvoicingsummaryexternalResponseCompound.");

            if (pkiEzmaxinvoicingsummaryexternalID.IsSet && pkiEzmaxinvoicingsummaryexternalID.Value == null)
                throw new ArgumentNullException(nameof(pkiEzmaxinvoicingsummaryexternalID), "Property is not nullable for class EzmaxinvoicingsummaryexternalResponseCompound.");

            if (fkiEzmaxinvoicingID.IsSet && fkiEzmaxinvoicingID.Value == null)
                throw new ArgumentNullException(nameof(fkiEzmaxinvoicingID), "Property is not nullable for class EzmaxinvoicingsummaryexternalResponseCompound.");

            return new EzmaxinvoicingsummaryexternalResponseCompound(fkiBillingentityexternalID.Value!.Value!, sBillingentityexternalDescription.Value!, sEzmaxinvoicingsummaryexternalDescription.Value!, aObjEzmaxinvoicingsummaryexternaldetail.Value!, pkiEzmaxinvoicingsummaryexternalID, fkiEzmaxinvoicingID);
        }

        /// <summary>
        /// Serializes a <see cref="EzmaxinvoicingsummaryexternalResponseCompound" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ezmaxinvoicingsummaryexternalResponseCompound"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EzmaxinvoicingsummaryexternalResponseCompound ezmaxinvoicingsummaryexternalResponseCompound, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ezmaxinvoicingsummaryexternalResponseCompound, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EzmaxinvoicingsummaryexternalResponseCompound" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ezmaxinvoicingsummaryexternalResponseCompound"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EzmaxinvoicingsummaryexternalResponseCompound ezmaxinvoicingsummaryexternalResponseCompound, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ezmaxinvoicingsummaryexternalResponseCompound.SBillingentityexternalDescription == null)
                throw new ArgumentNullException(nameof(ezmaxinvoicingsummaryexternalResponseCompound.SBillingentityexternalDescription), "Property is required for class EzmaxinvoicingsummaryexternalResponseCompound.");

            if (ezmaxinvoicingsummaryexternalResponseCompound.SEzmaxinvoicingsummaryexternalDescription == null)
                throw new ArgumentNullException(nameof(ezmaxinvoicingsummaryexternalResponseCompound.SEzmaxinvoicingsummaryexternalDescription), "Property is required for class EzmaxinvoicingsummaryexternalResponseCompound.");

            if (ezmaxinvoicingsummaryexternalResponseCompound.AObjEzmaxinvoicingsummaryexternaldetail == null)
                throw new ArgumentNullException(nameof(ezmaxinvoicingsummaryexternalResponseCompound.AObjEzmaxinvoicingsummaryexternaldetail), "Property is required for class EzmaxinvoicingsummaryexternalResponseCompound.");

            writer.WriteNumber("fkiBillingentityexternalID", ezmaxinvoicingsummaryexternalResponseCompound.FkiBillingentityexternalID);

            writer.WriteString("sBillingentityexternalDescription", ezmaxinvoicingsummaryexternalResponseCompound.SBillingentityexternalDescription);

            writer.WriteString("sEzmaxinvoicingsummaryexternalDescription", ezmaxinvoicingsummaryexternalResponseCompound.SEzmaxinvoicingsummaryexternalDescription);

            writer.WritePropertyName("a_objEzmaxinvoicingsummaryexternaldetail");
            JsonSerializer.Serialize(writer, ezmaxinvoicingsummaryexternalResponseCompound.AObjEzmaxinvoicingsummaryexternaldetail, jsonSerializerOptions);
            if (ezmaxinvoicingsummaryexternalResponseCompound.PkiEzmaxinvoicingsummaryexternalIDOption.IsSet)
                writer.WriteNumber("pkiEzmaxinvoicingsummaryexternalID", ezmaxinvoicingsummaryexternalResponseCompound.PkiEzmaxinvoicingsummaryexternalIDOption.Value!.Value);

            if (ezmaxinvoicingsummaryexternalResponseCompound.FkiEzmaxinvoicingIDOption.IsSet)
                writer.WriteNumber("fkiEzmaxinvoicingID", ezmaxinvoicingsummaryexternalResponseCompound.FkiEzmaxinvoicingIDOption.Value!.Value);
        }
    }
}
