/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.9
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = eZmaxApi.Client.OpenAPIDateConverter;

namespace eZmaxApi.Model
{
    /// <summary>
    /// EzsigndocumentGetWordsPositionsV1ResponseAllOf
    /// </summary>
    [DataContract]
    public partial class EzsigndocumentGetWordsPositionsV1ResponseAllOf :  IEquatable<EzsigndocumentGetWordsPositionsV1ResponseAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EzsigndocumentGetWordsPositionsV1ResponseAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EzsigndocumentGetWordsPositionsV1ResponseAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EzsigndocumentGetWordsPositionsV1ResponseAllOf" /> class.
        /// </summary>
        /// <param name="mPayload">Payload for POST /1/object/ezsigndocument/{pkiEzsigndocumentID}/getWordsPositions (required).</param>
        public EzsigndocumentGetWordsPositionsV1ResponseAllOf(List<CustomWordPositionWordResponse> mPayload = default(List<CustomWordPositionWordResponse>))
        {
            // to ensure "mPayload" is required (not null)
            if (mPayload == null)
            {
                throw new InvalidDataException("mPayload is a required property for EzsigndocumentGetWordsPositionsV1ResponseAllOf and cannot be null");
            }
            else
            {
                this.MPayload = mPayload;
            }

        }

        /// <summary>
        /// Payload for POST /1/object/ezsigndocument/{pkiEzsigndocumentID}/getWordsPositions
        /// </summary>
        /// <value>Payload for POST /1/object/ezsigndocument/{pkiEzsigndocumentID}/getWordsPositions</value>
        [DataMember(Name="mPayload", EmitDefaultValue=true)]
        public List<CustomWordPositionWordResponse> MPayload { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EzsigndocumentGetWordsPositionsV1ResponseAllOf {\n");
            sb.Append("  MPayload: ").Append(MPayload).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EzsigndocumentGetWordsPositionsV1ResponseAllOf);
        }

        /// <summary>
        /// Returns true if EzsigndocumentGetWordsPositionsV1ResponseAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of EzsigndocumentGetWordsPositionsV1ResponseAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EzsigndocumentGetWordsPositionsV1ResponseAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MPayload == input.MPayload ||
                    this.MPayload != null &&
                    input.MPayload != null &&
                    this.MPayload.SequenceEqual(input.MPayload)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MPayload != null)
                    hashCode = hashCode * 59 + this.MPayload.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
