/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = eZmaxApi.Client.OpenAPIDateConverter;

namespace eZmaxApi.Model
{
    /// <summary>
    /// An Ezsigntemplatedocument Object
    /// </summary>
    [DataContract(Name = "ezsigntemplatedocument-RequestPatch")]
    public partial class EzsigntemplatedocumentRequestPatch : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EzsigntemplatedocumentRequestPatch" /> class.
        /// </summary>
        /// <param name="sEzsigntemplatedocumentName">The name of the Ezsigntemplatedocument..</param>
        public EzsigntemplatedocumentRequestPatch(string sEzsigntemplatedocumentName = default(string))
        {
            this.SEzsigntemplatedocumentName = sEzsigntemplatedocumentName;
        }

        /// <summary>
        /// The name of the Ezsigntemplatedocument.
        /// </summary>
        /// <value>The name of the Ezsigntemplatedocument.</value>
        /* <example>Standard Contract</example>*/
        [DataMember(Name = "sEzsigntemplatedocumentName", EmitDefaultValue = false)]
        public string SEzsigntemplatedocumentName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EzsigntemplatedocumentRequestPatch {\n");
            sb.Append("  SEzsigntemplatedocumentName: ").Append(SEzsigntemplatedocumentName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
