/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.7
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = eZmaxApi.Client.OpenAPIDateConverter;

namespace eZmaxApi.Model
{
    /// <summary>
    /// Request for PUT /1/object/ezsigndocument/{pkiEzsigndocumentID}/editEzsignformfieldgroups
    /// </summary>
    [DataContract]
    public partial class EzsigndocumentEditEzsignformfieldgroupsV1Request :  IEquatable<EzsigndocumentEditEzsignformfieldgroupsV1Request>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EzsigndocumentEditEzsignformfieldgroupsV1Request" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EzsigndocumentEditEzsignformfieldgroupsV1Request() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EzsigndocumentEditEzsignformfieldgroupsV1Request" /> class.
        /// </summary>
        /// <param name="aObjEzsignformfieldgroup">aObjEzsignformfieldgroup (required).</param>
        public EzsigndocumentEditEzsignformfieldgroupsV1Request(List<EzsignformfieldgroupRequestCompound> aObjEzsignformfieldgroup = default(List<EzsignformfieldgroupRequestCompound>))
        {
            // to ensure "aObjEzsignformfieldgroup" is required (not null)
            if (aObjEzsignformfieldgroup == null)
            {
                throw new InvalidDataException("aObjEzsignformfieldgroup is a required property for EzsigndocumentEditEzsignformfieldgroupsV1Request and cannot be null");
            }
            else
            {
                this.AObjEzsignformfieldgroup = aObjEzsignformfieldgroup;
            }

        }

        /// <summary>
        /// Gets or Sets AObjEzsignformfieldgroup
        /// </summary>
        [DataMember(Name="a_objEzsignformfieldgroup", EmitDefaultValue=true)]
        public List<EzsignformfieldgroupRequestCompound> AObjEzsignformfieldgroup { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EzsigndocumentEditEzsignformfieldgroupsV1Request {\n");
            sb.Append("  AObjEzsignformfieldgroup: ").Append(AObjEzsignformfieldgroup).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EzsigndocumentEditEzsignformfieldgroupsV1Request);
        }

        /// <summary>
        /// Returns true if EzsigndocumentEditEzsignformfieldgroupsV1Request instances are equal
        /// </summary>
        /// <param name="input">Instance of EzsigndocumentEditEzsignformfieldgroupsV1Request to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EzsigndocumentEditEzsignformfieldgroupsV1Request input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AObjEzsignformfieldgroup == input.AObjEzsignformfieldgroup ||
                    this.AObjEzsignformfieldgroup != null &&
                    input.AObjEzsignformfieldgroup != null &&
                    this.AObjEzsignformfieldgroup.SequenceEqual(input.AObjEzsignformfieldgroup)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AObjEzsignformfieldgroup != null)
                    hashCode = hashCode * 59 + this.AObjEzsignformfieldgroup.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
