// <auto-generated>
/*
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using eZmaxApi.Client;

namespace eZmaxApi.Model
{
    /// <summary>
    /// Description of the API Key
    /// </summary>
    public partial class MultilingualApikeyDescription : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultilingualApikeyDescription" /> class.
        /// </summary>
        /// <param name="sApikeyDescription1">The description of the Apikey in French</param>
        /// <param name="sApikeyDescription2">The description of the Apikey in English</param>
        [JsonConstructor]
        public MultilingualApikeyDescription(Option<string?> sApikeyDescription1 = default, Option<string?> sApikeyDescription2 = default)
        {
            SApikeyDescription1Option = sApikeyDescription1;
            SApikeyDescription2Option = sApikeyDescription2;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SApikeyDescription1
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SApikeyDescription1Option { get; private set; }

        /// <summary>
        /// The description of the Apikey in French
        /// </summary>
        /// <value>The description of the Apikey in French</value>
        /* <example>Projet X</example> */
        [JsonPropertyName("sApikeyDescription1")]
        public string? SApikeyDescription1 { get { return this.SApikeyDescription1Option; } set { this.SApikeyDescription1Option = new(value); } }

        /// <summary>
        /// Used to track the state of SApikeyDescription2
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SApikeyDescription2Option { get; private set; }

        /// <summary>
        /// The description of the Apikey in English
        /// </summary>
        /// <value>The description of the Apikey in English</value>
        /* <example>Project X</example> */
        [JsonPropertyName("sApikeyDescription2")]
        public string? SApikeyDescription2 { get { return this.SApikeyDescription2Option; } set { this.SApikeyDescription2Option = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MultilingualApikeyDescription {\n");
            sb.Append("  SApikeyDescription1: ").Append(SApikeyDescription1).Append("\n");
            sb.Append("  SApikeyDescription2: ").Append(SApikeyDescription2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MultilingualApikeyDescription" />
    /// </summary>
    public class MultilingualApikeyDescriptionJsonConverter : JsonConverter<MultilingualApikeyDescription>
    {
        /// <summary>
        /// Deserializes json to <see cref="MultilingualApikeyDescription" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MultilingualApikeyDescription Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> sApikeyDescription1 = default;
            Option<string?> sApikeyDescription2 = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sApikeyDescription1":
                            sApikeyDescription1 = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sApikeyDescription2":
                            sApikeyDescription2 = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (sApikeyDescription1.IsSet && sApikeyDescription1.Value == null)
                throw new ArgumentNullException(nameof(sApikeyDescription1), "Property is not nullable for class MultilingualApikeyDescription.");

            if (sApikeyDescription2.IsSet && sApikeyDescription2.Value == null)
                throw new ArgumentNullException(nameof(sApikeyDescription2), "Property is not nullable for class MultilingualApikeyDescription.");

            return new MultilingualApikeyDescription(sApikeyDescription1, sApikeyDescription2);
        }

        /// <summary>
        /// Serializes a <see cref="MultilingualApikeyDescription" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="multilingualApikeyDescription"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MultilingualApikeyDescription multilingualApikeyDescription, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, multilingualApikeyDescription, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MultilingualApikeyDescription" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="multilingualApikeyDescription"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MultilingualApikeyDescription multilingualApikeyDescription, JsonSerializerOptions jsonSerializerOptions)
        {
            if (multilingualApikeyDescription.SApikeyDescription1Option.IsSet && multilingualApikeyDescription.SApikeyDescription1 == null)
                throw new ArgumentNullException(nameof(multilingualApikeyDescription.SApikeyDescription1), "Property is required for class MultilingualApikeyDescription.");

            if (multilingualApikeyDescription.SApikeyDescription2Option.IsSet && multilingualApikeyDescription.SApikeyDescription2 == null)
                throw new ArgumentNullException(nameof(multilingualApikeyDescription.SApikeyDescription2), "Property is required for class MultilingualApikeyDescription.");

            if (multilingualApikeyDescription.SApikeyDescription1Option.IsSet)
                writer.WriteString("sApikeyDescription1", multilingualApikeyDescription.SApikeyDescription1);

            if (multilingualApikeyDescription.SApikeyDescription2Option.IsSet)
                writer.WriteString("sApikeyDescription2", multilingualApikeyDescription.SApikeyDescription2);
        }
    }
}
